version: "3.9"
services:
  base:
    image: node:14.15.4
    volumes:
      - nodemodules:/usr/src/app/node_modules
      - .:/usr/src/app
    working_dir: /usr/src/app
  install:
    extends:
      service: base
    command: npm install
  build:
    extends:
      service: base
    command: npm run build
volumes:
  nodemodules:
    external: true